### PR TITLE
added Connectivity support for Xamarin.Mac

### PR DESCRIPTION
**Pull request by NateRickard**

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Is all the code the same from the iOS version? Could we use file linking if so?

**Comment by NateRickard** [comment]
It's slightly different since there's no 4g/ReachableViaCarrierDataNetwork support.

**Comment by jamesmontemagno** [comment]
Gotcha... wondering if we could just do some #if condition statements so it is all the same code besides a few types.

**Comment by NateRickard** [comment]
You could definitely go that route, but there are a few if/switch statements that would need to be #if'd around.  I thought about going that direction but was looking for an easy merge and wanted to leave the iOS code alone.

**Pull request merged**
