### PR TITLE
Add ActivityType (iOS).

### LINKED ISSUE #236: Location update pausing does not set activity type (iOS)
I've got a pull request coming to fix the following...

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:  3.1.0-beta
Device Tested On:  LG G3
Simulator Tested On:  None

### Expected Behavior
When pausing location updates on iOS, locator should indicate the activity type to use.

### Actual Behavior
iOS locator does not set the activity type.

### Steps to reproduce the Behavior
Start iOS location update listener with location update pausing enabled.

### PR DESCRIPTION
**Pull request by MatthewGerber**
Fixes #236.

Changes Proposed in this pull request:
Add ActivityType to Geolocator.

This fixes/implements:
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [x] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@jamesmontemagno Can you please take a look and release as 3.1.0-beta2 if you think it looks okay?

**Comment by jamesmontemagno** [comment]
Is this a required setting? What happens if they don't set it today? Should we make them pass it in? It seems like we should change "ListenerEnergySettings" to "ListeningSettings" so we can just throw a bunch of stuff on there to be honest

**Comment by MatthewGerber** [comment]
That's exactly what I'm planning to do... Stay tuned

**Comment by MatthewGerber** [comment]
@jamesmontemagno The most appropriate solution for this will introduce breaking changes (e.g., moving `PausesLocationUpdatesAutomatically` to `ListenerSettings`). Can we move to 4.0.0 or do I need to keep it backwards compatible (not as pretty)?

**Comment by jamesmontemagno** [comment]
Sounds good to me. I am all about doing it right... for the greater good :)

Should the distance be in there too?

PausesLocationUpdatesAutomatically doesn't impact getting the location 1
time does it?

James

On Wed, Mar 2, 2016 at 6:41 PM, Matthew Gerber <notifications@github.com>
wrote:

> @jamesmontemagno <https://github.com/jamesmontemagno> The most
> appropriate solution for this will introduce breaking changes (e.g., moving
> PausesLocationUpdatesAutomatically to ListenerSettings). Can we move to
> 4.0.0 or do I need to keep it backwards compatible (not as pretty)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/pull/237#issuecomment-191550322>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by MatthewGerber** [comment]
The distance and a few other things will be in there. None of these settings should affect the ability to get location one time via `GetPositionAsync`. They should only impact listening. Should have this ready tomorrow sometime.

**Comment by MatthewGerber** [comment]
@jamesmontemagno Okay, ready for you to take a look. Here's how I approached it.

`CLLocationManager` has a set of properties that dictate when, how often, and how accurately location updates are delivered. These properties should only affect `StartListeningAsync`. These properties should not affect `GetPositionAsync` since the caller is expecting to receive a single location update as quickly as possible. So, I have collected all of the properties into a new `ListenerSettings` class (used to be `EnergySettings`), an instance of which is passed to `StartListeningAsync`. Within `StartListeningAsync`, the locator is configured with the settings that are passed in and we're off. Some of the properties that are now in `ListenerSettings` used to be in `IGeolocator`, simplifying many of the `GeolocatorImplementation` classes (all of this stuff is specific to iOS).

The upshot is that the iOS version now support pausing location updates by activity type, listening for significant changes (cell tower bindings), and deferred delivery of updates.

**Comment by jamesmontemagno** [comment]
If we are going to do a 4.0 I would love to make more breaking changes and move all times to TimeSpan :)

**Comment by jamesmontemagno** [comment]
What else can we cleanup?

**Comment by jamesmontemagno** [comment]
Can you add onto this: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/243

**Comment by MatthewGerber** [comment]
@jamesmontemagno When you say "move all times to TimeSpan", what do you have in mind? Are you thinking `minTime` from `public Task<bool> StartListeningAsync(int minTime, double minDistance, bool includeHeading = false, ListenerSettings settings = null)`?

Other things?

**Comment by jamesmontemagno** [comment]
I think it should be like:

Task<bool> StartListeningAsync(TimeSpan minimumTime, double minimumMeters,
bool includeHeading = false, ListenerSettings settings = null)

or just do this:

Task<bool> StartListeningAsync(ListenerSettings settings = null)

and go from there with some good defaults.

James

On Fri, Mar 4, 2016 at 3:21 PM, Matthew Gerber <notifications@github.com>
wrote:

> @jamesmontemagno <https://github.com/jamesmontemagno> When you say "move
> all times to TimeSpan", what do you have in mind? Are you thinking minTime
> from public Task<bool> StartListeningAsync(int minTime, double
> minDistance, bool includeHeading = false, ListenerSettings settings = null)
> ?
>
> Other things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesmontemagno/Xamarin.Plugins/pull/237#issuecomment-192517241>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by MatthewGerber** [comment]
@jamesmontemagno Got it. I don't think I'll have time to do this extra stuff for a while. Could you please release the 4.0.0-beta1 Nuget in the meantime so that I can begin testing the current changes for iOS location listening?

**Comment by jamesmontemagno** [comment]
I will do this, this weekend and continue to make changes throughout the
week for 4.0.0

**Comment by MatthewGerber** [comment]
@jamesmontemagno I've been testing the 4.0.0-beta1 release. So far I've only tested location update deferrals. You can see actual GPS traces here for two different deferral settings:

http://mgo.ms/s/4wiwn

Turn on the two series in the legend and compare. The purple series shows location deferral at 5000 meters and 5 minutes. The dense purple clusters are approximately 5000 meters apart. The green series shows location deferral at 1000 meters and 5 minutes. The dense green clusters are approximately 1000 meters apart. All freeway driving was continuous at around 70 mp/h. The clustering pattern is pretty regular; however, there are some stray location updates between the dense clusters on the freeway. I'm not sure why. There are also some location updates far from the freeway. I think these are cell tower locations.

Just FYI. I think deferral is working properly. I'll be looking at location update pausing next.

**Pull request merged**
