### PR TITLE
Net45 implementation of Settings

### PR DESCRIPTION
**Pull request by brainoffline**
I use the .Net 45 MsTest for my unit testing framework.  This allows us to run CI in the cloud.

When I wrote a unit test that relied on Settings then it failed as there was only the portable implementation.  

This pull request includes code for .Net45 project for the concrete implementation and additional msunit tests.

I have not changed any version information

### CODE REVIEW

**Comment by lsmithmier** [comment]
Thanks for this!  It allowed me to add unit testing.

**Comment by Axel3232** [comment]
Is this PR in production, I am unable to launch unit test in my MsTest 4.5 project... having SystemNotImplementedException ??

**Comment by jamesmontemagno** [comment]
This is not in production, but I will look into it. Take a look into testing: http://www.michaelridland.com/xamarin/best-practices-using-xamarin-plugins/ with plugins

**Comment by jamesmontemagno** [comment]
Now integrated into latest version

**Pull request closed without merging**
