### PR TITLE
[Settings] DateTimeKind correctly set to UTC

### PR DESCRIPTION
**Pull request by LorenzCK**
When restoring DateTime values from the settings they are now correctly set with `DateTimeKind.Utc`.

# Rationale #

When restoring an UTC DateTime as `Unspecified` (as done by default) and using it as a UTC timestamp (for instance when passing the DateTime value to an API requiring UTC values), the UTC offset may be applied multiple times.
Storing and restoring DateTime values using the UTC timezone ensures that the timezone is always applied correctly (even when `DateTime.ToUniversalTime` is called multiple times).

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I am interested in bringing this in, but how will it impact existing installs that have DateTime saved out? Essentially will it effect what the developer is expecting?

**Comment by LorenzCK** [comment]
Yes, but you would essentially be trading one unexpected conversion for another.

At the moment values stored by the plug-in are retrieved as `DateTimeKind.Unspecified`, which means that [as per documentation](https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx#Anchor_1) they get converted (i.e. the UTC offset is applied) both by `ToUniversalTime()` **and** `ToLocalTime()`.
This is particularly noticeable when comparing any date retrieved through the plug-in:

    var future = new DateTime(DateTime.UtcNow.Add(TimeSpan.FromMinutes(1)).Ticks, DateTimeKind.Unspecified);
    future > DateTime.Now; // false
    future > DateTime.UtcNow; // true
    
    var past = new DateTime(DateTime.Now.Subtract(TimeSpan.FromMinutes(1)).Ticks, DateTimeKind.Unspecified);
    past < DateTime.Now; // true
    past < DateTime.UtcNow; // false

Essentially, developers are already impacted inasmuch they are getting `DateTime` values on which arithmetic operations can be correct only by accident. (But if, for instance, an app uses only local dates it will probably never notice it.)

However, if you decide to bring in the change, settings currently saved out starting from a `DateTimeKind.Local` value will definitely be timezone-shifted to UTC until a new value is stored. (This might be *more* wrong, by some definition.)

One way to prevent this would be to store new UTC values as a negative tick count, in order to keep the original behavior for older values.
I don't think there would be unwanted effects, since ticks are always positive and the plug-in stores the values as signed longs on every platform AFAIK.

**Comment by LorenzCK** [comment]
I've just committed the changes mentioned above: new DateTime values are now stored using a negative UTC tick count. When retrieving DateTime values, if the tick count is positive, it is assumed the value was stored by the plug-in before these changes, and thus is returned with `DateTimeKind.Unspecified` as before.

New values will always be persisted and retrieved as UTC values.

**Comment by jamesmontemagno** [comment]
I still need some time to think about this one as the code seems to be getting more complicated as it goes on. For the old silverlight stuff it doesn't get impacted at all or should we be detecting they are passing a UTC stamp? If @praeclarum has any thoughts on this one?

**Comment by jamesmontemagno** [comment]
Can you squash your changes so I can see the final diff too? Sorry for being so stubborn on this one it is my most popular and long lasting plugin.

**Comment by jamesmontemagno** [comment]
Oh, never mind the squash.. my amazing Xamarins informed me there is a button that shows me this :)

**Comment by LorenzCK** [comment]
> For the old silverlight stuff it doesn't get impacted at all or should we be detecting they are passing a UTC stamp?

I just tested the library with a sample Silverlight 8.1 project and `DateTime` values are stored and retrieved correctly, leaving the original `DateTimeKind` intact (i.e., values expressed using a local timezone are read back as local values, some for UTC or unspecified values).

That platform shouldn't be impacted at all.

**Comment by jamesmontemagno** [comment]
lovely! oh yeah because I am not converting them. Makes sense to me. I am doing a 2.0 push which this will be included in :)

**Pull request merged**
